apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: performance

resources:
  - jmeter-logs-pvc.yaml
  - fastapp-logs-pvc.yaml
  - ../../base

patches:
  - path: logstash-patch.yaml
  - path: filebeat-patch.yaml
    target:
       kind: Beat
       name: filebeat