apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  # namespace: performance
spec:
  type: filebeat
  version: 8.13.4

  config:
    filebeat.inputs: []
    output.logstash:
      hosts: ["logstash-ls-beats:5044"]

  daemonSet:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            imagePullPolicy: IfNotPresent
            volumeMounts: []
        volumes: []